alias submit="sudo sh ../../templates/submit.sh"
alias make_template="sudo sh ../../templates/make_template.sh"
alias gcj_init="python ../../codejam-commandline-1.2-beta1/gcj_init_contest.py `cat ID`"
alias gcj_input="python ../../codejam-commandline-1.2-beta1/gcj_download_input.py"
alias gcj_all_inputs="gcj_init && gcj_input A large 0 && gcj_input A small 0 && gcj_input A large 0 && gcj_input B small 0 && gcj_input B large 0 && gcj_input C small 0 && gcj_input C large 0"
alias gcj_submit="python ../../codejam-commandline-1.2-beta1/gcj_submit_solution.py"
